name: unicorn_cafe
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  shared_preferences: ^2.2.0
  google_fonts: ^5.1.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  email_validator: ^2.1.17
  font_awesome_flutter: ^10.5.0
  fluttertoast: ^8.2.2
  dartz: ^0.10.1
  fpdart: ^0.6.0
  google_sign_in: ^6.1.4
  firebase_storage: ^11.2.5
  firebase_database: ^10.2.4
  loading:
    git:
      url: https://github.com/smit13192/loading.git
      ref: master
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/png/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
