// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAmUfsdh_Qme8C8DiE6SEEE4AlWLmCWnc',
    appId: '1:726827495376:web:c66460ad753a4db348d3d5',
    messagingSenderId: '726827495376',
    projectId: 'unicorn-cafe-a22d2',
    authDomain: 'unicorn-cafe-a22d2.firebaseapp.com',
    storageBucket: 'unicorn-cafe-a22d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa68vglWa_fki3qcu8UhKbzuCKOsOSKQo',
    appId: '1:726827495376:android:24167c00302434c048d3d5',
    messagingSenderId: '726827495376',
    projectId: 'unicorn-cafe-a22d2',
    storageBucket: 'unicorn-cafe-a22d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIy2-llDow41QKSTcRs_fD_kePN75QyOg',
    appId: '1:726827495376:ios:3ffb1562cd5855b848d3d5',
    messagingSenderId: '726827495376',
    projectId: 'unicorn-cafe-a22d2',
    storageBucket: 'unicorn-cafe-a22d2.appspot.com',
    iosClientId: '726827495376-h703dpav8h7f1hdpkkne5ovist675uh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.unicornCafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIy2-llDow41QKSTcRs_fD_kePN75QyOg',
    appId: '1:726827495376:ios:26168be252dc4c3c48d3d5',
    messagingSenderId: '726827495376',
    projectId: 'unicorn-cafe-a22d2',
    storageBucket: 'unicorn-cafe-a22d2.appspot.com',
    iosClientId: '726827495376-vngpq28t09cot846c3rfjd75k56u5ole.apps.googleusercontent.com',
    iosBundleId: 'com.example.unicornCafe.RunnerTests',
  );
}
